### ISSUE TITLE
Difference between views and schema

### ISSUE THREAD

**Issue by brookeangel** [shph119/LiftWithMe#1]
Looks like your GymSessionForm lists exercises but your schema does not - are you planning on having a separate model for exercises? If so - make sure your schema lists it out.

**Comment by sang-park** [comment]
I don't know if I'll have a separate model... I would just need to make a table of exercises, and have a join table for each workout. I think it would make the most sense for me to have a populated table of exercises, then have users choose from that list, and just input the sets/reps, and store that information in the joint table.

**Comment by sang-park** [comment]
Hmm... do you think it would be better if I just stored all the exercise information with the GymSessions? I guess I would need to make additional requests for the join table if i kept them separately, but I dont think that'll be too much of an issue. 
If I go with the previous route, my GymSession would only have access to the muscle group, and to excess the exercises themselves, you would need to go into the join table, which can be put into the detailView

**Comment by brookeangel** [comment]
I think it may make sense to have a populated table of exercises as you said and use a join table that lists number of reps and sets rather than just storing it all with gym sessions - it's a lot of info and it seems like a many to many relationship to me so a join table would be the way to go. Just make sure to add it to your schema. Look into "accepts_nested_attributes_for" which is a Rails method - it should prevent you from needing to make additional requests. You will still need to create models for validations and associations, but will not have to create an exercises controller.
